services:
  cloudflared:
    image: ${DOCKER_MIRROR}docker.io/wisdomsky/cloudflared-web:${VERSION}
    container_name: cloudflared
    network_mode: host
    volumes:
      - ${TRIM_PKGVAR:?}/config:/config
      - ${TRIM_PKGVAR:?}/cloudflared:/root/.cloudflared
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped